version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'bootdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
      - '33060:33060'
    expose:
      - '3306'
      - '33060'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - inatel

  stock-manager:
    image: adautomendes/stock-manager
    container_name: stock-manager
    ports:
      - 8080:8080
    environment:
      - SERVER_HOST=stock-manager
      - SERVER_PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql
    networks:
      - inatel

volumes:
  my-db:

networks:
  inatel:
    name: inatel